networks:    
  agience-net:
    name: agience-net
    driver: bridge

volumes:
  authority-data:
  icecast-logs:

services:
    
  database-sql:  
    container_name: database-sql
    image: database-sql
    restart: on-failure
    build:
      context: ./database-sql
    environment:      
      - POSTGRES_DB=${AUTHORITY_DATABASE_NAME:-agience-authority}
      - POSTGRES_USER=${AUTHORITY_DATABASE_USERNAME:-}
      - POSTGRES_PASSWORD=${AUTHORITY_DATABASE_PASSWORD:-}
    ports:
      - "5432:5432"
    volumes:      
      - authority-data:/var/lib/postgresql/data
    networks:
      - agience-net
      
  broker-mqtt:
    container_name: broker-mqtt
    image: broker-mqtt
    restart: on-failure
    build:
      context: ./broker-mqtt
    environment:
      - AUTHORITY_HOST=${AUTHORITY_HOST:-identity-api}
      - AUTHORITY_PORT=${AUTHORITY_PORT:-5001}
      - BROKER_AUTH_LOG_LEVEL=${BROKER_AUTH_LOG_LEVEL:-info}
      - BROKER_JWT_GETUSER_PATH=${BROKER_JWT_GETUSER_PATH:-/broker/connect/check}
      - BROKER_JWT_ACLCHECK_PATH=${BROKER_JWT_ACLCHECK_PATH:-/broker/acl/check}
      - BROKER_MQTT_LISTEN_PORT=${BROKER_MQTT_LISTEN_PORT:-1883}
      - BROKER_WS_LISTEN_PORT=${BROKER_WS_LISTEN_PORT:-1884}
    ports:
      - "1883:1883"
      - "1884:1884"
    networks:
      - agience-net
    depends_on:
      - database-sql
      - identity-api

  identity-api:
    container_name: identity-api
    image: identity-api
    restart: on-failure
    build:
      context: ../
      dockerfile: ./authority/identity-api-dotnet/Dockerfile
    ports:
      - "5001:5001"    
    networks:
      - agience-net
    depends_on:      
      - database-sql

  manage:
    container_name: manage-ui
    image: manage-ui
    restart: on-failure
    build:
      context: ./manage-ui
    ports:
      - "5002:5002"
    networks:
      - agience-net

#  stream:
#    container_name: media-stream
#    image: media-stream
#    restart: on-failure
#    build:      
#      dockerfile: media-stream/Dockerfile            
#    ports:
#      - "8000:8000"
#    volumes:
#      - icecast-logs:/var/log/icecast
#    networks:
#      - agience-net
#    depends_on:
#      - "identity"