networks:
    
  agience-net:
    name: agience-net
    driver: bridge

volumes:  
    
  authority-data:    
  icecast-logs:
   
services:
    
  identity:  
    container_name: identity-cont    
    networks:
      - agience-net
    depends_on:
      - "broker"
      - "database"

  manage:
    container_name: manage-cont
    networks:
      - agience-net
    depends_on:
      - "identity"
      
  database:
    container_name: database-cont
    networks:
      - agience-net

  broker:
    container_name: broker-cont
    networks:
      - agience-net
    depends_on:
      - "database"
   
  stream:          
    container_name: stream-cont
    networks:
      - agience-net
    depends_on:
      - "database"
 