networks:
    
  agience-net:
    driver: bridge

volumes:  
    
  authority-data:    
  icecast-logs:
   
services:
    
  identity:          
    networks:
      - agience-net
    depends_on:
      - "broker"
      - "database"

  manage:
    networks:
      - agience-net
      
  database:
    networks:
      - agience-net

  broker:
    networks:
      - agience-net
    depends_on:
      - "database"
   
  stream:          
    networks:
      - agience-net
    depends_on:
      - "database"
 