networks:
    
  agience-net:
    name: agience-net-debug

services:
    
  identity:
    container_name: identity-debug
    image: identity:debug
    restart: on-failure
    build:
      context: ../..
      dockerfile: Authority/Identity/Dockerfile     
      args:
        BUILD_ENVIRONMENT: debug
    ports:
      - "0.0.0.0:5001:5001"
    environment:
      - AGIENCE_INITIALIZE=${AGIENCE_INITIALIZE:-false}
    env_file:
      - ../Identity/.env.debug
    volumes:
      - ../Build/certs/localhost.pfx:/app/https/localhost.pfx:ro
      - ../Build/certs/agience-debug.pfx:/app/https/agience-debug.pfx:ro
      - ../Build/certs/agience-debug.crt:/usr/local/share/ca-certificates/agience-debug.crt:ro
    entrypoint: /bin/bash -c "update-ca-certificates && exec dotnet Agience.Authority.Identity.dll"

      
  database:  
    container_name: database-debug
    image: database:debug
    restart: always  
    build:
      context: ../..
      dockerfile: Authority/Database/Dockerfile     
      args:
        BUILD_ENVIRONMENT: debug
    env_file:
      - ../Database/.env.debug
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ../Build/certs/agience-debug.crt:/etc/postgresql/certs/certfile.crt
      - ../Build/certs/agience-debug.key:/etc/postgresql/certs/keyfile.key
      - authority-data:/var/lib/postgresql/data

  broker:
    container_name: broker-debug  
    image: broker:debug
    restart: always  
    build:
      context: ../..
      dockerfile: Authority/Broker/Dockerfile
      args:
        BUILD_ENVIRONMENT: debug
    ports:      
      - "0.0.0.0:1884:1884"
    volumes:
      - ../Build/certs/localhost.crt:/etc/mosquitto/certs/localhost.crt
      - ../Build/certs/localhost.key:/etc/mosquitto/certs/localhost.key
      - ../Build/certs/localhost.crt:/usr/local/share/ca-certificates/localhost.crt
      - ../Build/certs/agience-debug.crt:/etc/mosquitto/certs/agience-debug.crt
      - ../Build/certs/agience-debug.key:/etc/mosquitto/certs/agience-debug.key
      - ../Build/certs/agience-debug.crt:/usr/local/share/ca-certificates/agience-debug.crt
      

  stream:
    container_name: stream-debug
    image: stream:debug
    restart: always  
    build:      
      context: ../..
      dockerfile: Authority/Stream/Dockerfile      
      args:
        BUILD_ENVIRONMENT: debug
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ../Stream/icecast.debug.xml:/etc/icecast.xml:ro
      - ../Stream/icecast.debug.secrets.xml:/etc/icecast.secrets.xml:ro
      - icecast-logs:/var/log/icecast
