networks:
    
  agience-net:
    name: agience-net-local

services:
    
  identity:
    container_name: identity-local  
    image: identity:local  
    restart: always
    build:
      context: ../..
      dockerfile: Authority/Identity/Dockerfile     
      args:
        BUILD_ENVIRONMENT: local
    environment:
      - AGIENCE_INITIALIZE=${AGIENCE_INITIALIZE:-false}
    env_file:
      - ../Identity/.env.local
    volumes:
      - ../Build/certs/agience-local.pfx:/app/https/agience-local.pfx
      - ../Build/certs/agience-local.crt:/usr/local/share/ca-certificates/agience-local.crt
    entrypoint: /bin/bash -c "update-ca-certificates && exec dotnet Agience.Authority.Identity.dll"

  database:
    container_name: database-local  
    image: database:local    
    restart: always  
    build:
      context: ../..
      dockerfile: Authority/Database/Dockerfile     
      args:
        BUILD_ENVIRONMENT: local     
    env_file:
      - ../Database/.env.local
    volumes:
      -  authority-data:/var/lib/postgresql/data
      - ../Build/certs/agience-local.crt:/etc/postgresql/certs/certfile.crt
      - ../Build/certs/agience-local.key:/etc/postgresql/certs/keyfile.key

  broker:
    container_name: broker-local  
    image: broker:local  
    restart: always  
    build:
      context: ../..
      dockerfile: Authority/Broker/Dockerfile
      args:
        BUILD_ENVIRONMENT: local
    volumes:
      - ../Build/certs/agience-local.crt:/etc/mosquitto/certs/agience-local.crt
      - ../Build/certs/agience-local.key:/etc/mosquitto/certs/agience-local.key
      - ../Build/certs/agience-local.crt:/usr/local/share/ca-certificates/agience-local.crt

  proxy:
    container_name: proxy-local  
    image: proxy:local    
    networks:
      - agience-net
    depends_on:      
      - "identity"
      - "manage"
      - "broker"
    restart: always  
    build:
      context: ../..
      dockerfile: Authority/Proxy/Dockerfile
      args:
        BUILD_ENVIRONMENT: local   
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:1884:1884"
      - "0.0.0.0:5001:5001"
      - "0.0.0.0:5002:5002"
      - "0.0.0.0:8000:8000"
    volumes:
      - ../Build/certs/local.agience.ai.crt:/etc/nginx/certs/public/local.agience.ai.crt
      - ../Build/certs/local.agience.ai.key:/etc/nginx/certs/public/local.agience.ai.key
      - ../Build/certs/agience-local.crt:/usr/local/share/ca-certificates/agience-local.crt

  stream:
    container_name: stream-local
    image: stream:local
    restart: always  
    build:      
      context: ../..
      dockerfile: Authority/Stream/Dockerfile      
      args:
        BUILD_ENVIRONMENT: local
    volumes:
      - ../Stream/icecast.local.xml:/etc/icecast.xml
      - ../Stream/icecast.local.secrets.xml:/etc/icecast.secrets.xml
      - icecast-logs:/var/log/icecast
