networks:
    
  agience-net:
    name: agience-net
    driver: bridge

volumes:  
    
  authority-data:
  icecast-logs:
   
services:
    
  identity:  
    image: identity:latest
    container_name: identity-cont    
    networks:
      - agience-net
    depends_on:
      - "broker"
      - "database"

  manage:
    image: manage:latest  
    container_name: manage-cont
    networks:
      - agience-net
    depends_on:
      - "identity"
      
  database:
    image: database:latest
    container_name: database-cont
    networks:
      - agience-net

  broker:
    image: broker:latest  
    container_name: broker-cont
    networks:
      - agience-net
    depends_on:
      - "database"

  proxy:
    image: proxy:latest
    container_name: proxy-cont
    networks:
      - agience-net
    depends_on:      
      - "identity"
      - "manage"
      - "broker"
   
  stream:          
    image: stream:latest
    container_name: stream-cont
    networks:
      - agience-net
    depends_on:
      - "database"
